### PR TITLE
Add optional TLS support for exporter

### PR DESCRIPTION
**Pull request by gmintoco**

### CODE REVIEW

**Comment by bmwilli** [comment]
Any chance this will get completed?

**Comment by nvvfedorov** [comment]
The changes were integrated into the main branch by another PR: https://github.com/NVIDIA/dcgm-exporter/pull/209. 

Thank you for your contribution.

**Comment by bmwilli** [comment]
Thanks for merging this.  Any estimate for when this will be in a release and available in a container?  Thank you so much!!

**Comment by nvvfedorov** [comment]
The target is the end of January or early February 2024.

**Pull request closed without merging**
