### PR TITLE
Rename 'secuity' to 'security'

### PR DESCRIPTION
**Pull request by remram44**

### CODE REVIEW

**Review by glowkey — APPROVED** [review]

**Comment by nvvfedorov** [comment]
@remram44 , Please sign your commit

**Comment by remram44** [comment]
Bump

**Comment by glowkey** [comment]
The commit needs to be signed (git commit -S) before it can be merged.

**Comment by remram44** [comment]
It is signed

**Comment by glowkey** [comment]
Check out this link: https://docs.github.com/authentication/managing-commit-signature-verification/about-commit-signature-verification You'll notice that this commit does not have the "Verified" tag.

**Comment by remram44** [comment]
[Your contributing guide](https://github.com/NVIDIA/dcgm-exporter/blob/main/CONTRIBUTING.md) says I need to "sign-off" commits, not GPG-sign them. Are you sure you are not confusing those?

**Pull request merged**
