### PR TITLE
Fix Helm Templates Generation

### PR DESCRIPTION
**Pull request by Indresh2410**
Issue: https://github.com/NVIDIA/dcgm-exporter/issues/405

### CODE REVIEW

**Review by glowkey — APPROVED** [review]

**Comment by glowkey** [comment]
The commit needs to be signed (git commit -S) before it can be merged.

**Comment by Indresh2410** [comment]
Hi @glowkey . Thanks for reviewing. The commit is already signed
https://github.com/NVIDIA/dcgm-exporter/pull/406/commits/2554e4cee39e63378b68e4179dc81109a58800aa

Not sure if we are missing something here. Can you please help here?

**Comment by glowkey** [comment]
Check out this link: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification
If you look at your commit, you'll notice it does not have the "Verified" tag.

**Comment by Indresh2410** [comment]
Thanks @glowkey . Addressed it. Thanks for pointing out 😄

**Pull request merged**
